language: node_js
node_js:
  - stable
cache: yarn
script:
  - node_modules/.bin/travis-github-status lint flow jest codeclimate # git.repos.createSatus(error count 4 tool)
notifications:
  email: false
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
